echo "GE"
cat close_price_GE.csv | tail -n 30 | awk -F "," '{sum+=$5;c++;}END{sum/=c;print sum}'
cat close_price_GE.csv | tail -n 30 | awk -F "," '{sum+=$6;c++;}END{sum/=c;print sum}'
cat close_price_GE.csv | tail -n 30 | awk -F "," '{sum+=$7;c++;}END{sum/=c;print sum}'
cat close_price_GE.csv | tail -n 30 | awk -F "," '{sum+=$8;c++;}END{sum/=c;print sum}'
cat close_price_GE.csv | tail -n 30 | awk -F "," '{sum+=$9;c++;}END{sum/=c;print sum}'
cat close_price_GE.csv | tail -n 30 | awk -F "," '{sum+=$10;c++;}END{sum/=c;print sum}'
cat close_price_GE.csv | tail -n 30 | awk -F "," '{sum+=$11;c++;}END{sum/=c;print sum}'
cat close_price_GE.csv | tail -n 30 | awk -F "," '{sum+=$12;c++;}END{sum/=c;print sum}'
cat close_price_GE.csv | tail -n 30 | awk -F "," '{sum+=$13;c++;}END{sum/=c;print sum}'
echo "I"
cat close_price_I.csv | tail -n 30 | awk -F "," '{sum+=$5;c++;}END{sum/=c;print sum}'
cat close_price_I.csv | tail -n 30 | awk -F "," '{sum+=$6;c++;}END{sum/=c;print sum}'
cat close_price_I.csv | tail -n 30 | awk -F "," '{sum+=$7;c++;}END{sum/=c;print sum}'
cat close_price_I.csv | tail -n 30 | awk -F "," '{sum+=$8;c++;}END{sum/=c;print sum}'
cat close_price_I.csv | tail -n 30 | awk -F "," '{sum+=$9;c++;}END{sum/=c;print sum}'
cat close_price_I.csv | tail -n 30 | awk -F "," '{sum+=$10;c++;}END{sum/=c;print sum}'
cat close_price_I.csv | tail -n 30 | awk -F "," '{sum+=$11;c++;}END{sum/=c;print sum}'
cat close_price_I.csv | tail -n 30 | awk -F "," '{sum+=$12;c++;}END{sum/=c;print sum}'
cat close_price_I.csv | tail -n 30 | awk -F "," '{sum+=$13;c++;}END{sum/=c;print sum}'
echo "L"
cat close_price_L.csv | tail -n 30 | awk -F "," '{sum+=$5;c++;}END{sum/=c;print sum}'
cat close_price_L.csv | tail -n 30 | awk -F "," '{sum+=$6;c++;}END{sum/=c;print sum}'
cat close_price_L.csv | tail -n 30 | awk -F "," '{sum+=$7;c++;}END{sum/=c;print sum}'
cat close_price_L.csv | tail -n 30 | awk -F "," '{sum+=$8;c++;}END{sum/=c;print sum}'
cat close_price_L.csv | tail -n 30 | awk -F "," '{sum+=$9;c++;}END{sum/=c;print sum}'
cat close_price_L.csv | tail -n 30 | awk -F "," '{sum+=$10;c++;}END{sum/=c;print sum}'
cat close_price_L.csv | tail -n 30 | awk -F "," '{sum+=$11;c++;}END{sum/=c;print sum}'
cat close_price_L.csv | tail -n 30 | awk -F "," '{sum+=$12;c++;}END{sum/=c;print sum}'
cat close_price_L.csv | tail -n 30 | awk -F "," '{sum+=$13;c++;}END{sum/=c;print sum}'
echo "BAX"
cat close_price_BAX.csv | tail -n 30 | awk -F "," '{sum+=$4;c++;}END{sum/=c;print sum}'
cat close_price_BAX.csv | tail -n 30 | awk -F "," '{sum+=$5;c++;}END{sum/=c;print sum}'
cat close_price_BAX.csv | tail -n 30 | awk -F "," '{sum+=$6;c++;}END{sum/=c;print sum}'
